<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create users
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->emailField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<!--<div class="form-group">-->
<!--    <label for="fieldRank" class="col-sm-2 control-label">Rank</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["rank", "size" => 30, "class" => "form-control", "id" => "fieldRank"]) ?>
<!--    </div>-->
<!--</div>-->

<div class="form-group">
    <label for="fieldRank" class="col-sm-2 control-label">Rank</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(
            [
                "rank",
                [
                    "raider" => "Raider",
                    "officer" => "Officer",
                    //Seperator
                    "admin" => "Admin",
                    "moderator" => "Moderator",
                ]
            ]
        );
        ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
