<link rel="stylesheet" type="text/css" href="css/style.css">

<div class="page-header">
	<h1>
		News
	</h1>
<!--	Create if statement that only shows when logged in and admin+-->
	<p>
		<?php echo $this->tag->linkTo(["news/new", "Create new post"]) ?>
	</p>
	<p>
		<?php echo $this->tag->linkTo(["news/manage", "Manage news"]) ?>

	</p>
</div>

<?php foreach ($page->items as $news): ?>

	<div class="title">
		<?php echo ucfirst($news->name) ?> <!--Automaticly capitilizes first letter of string-->
	</div>

	<div class="message">
		<?php echo ucfirst($news->message) ?> <!--Automaticly capitilizes first letter of string-->
	</div>

	<div class="creator">
		Created by: <?php echo ucfirst($news->users->username) ?> <!--Automaticly capitilizes first letter of string-->
	</div>
	<div class="delete">
		<?php echo $this->tag->linkTo(["news/delete/" . $news->id, "Delete", "class" => "btn btn-danger"]); ?>
	</div>
	<div class="divider"></div>


	<?php endforeach; ?>




<div class="row">
	<div class="col-sm-1">
		<p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
			<?php echo $page->current, "/", $page->total_pages ?>
		</p>
	</div>
	<div class="col-sm-11">
		<nav>
			<ul class="pagination">
				<li><?php echo $this->tag->linkTo("news", "First") ?></li>
				<li><?php echo $this->tag->linkTo("news?page=" . $page->before, "Previous") ?></li>
				<li><?php echo $this->tag->linkTo("news?page=" . $page->next, "Next") ?></li>
				<li><?php echo $this->tag->linkTo("news?page=" . $page->last, "Last") ?></li>
			</ul>
		</nav>
	</div>
</div>
