<div class="page-header">
	<h1>
		Create new post in News
	</h1>
	<p>
		<?php echo $this->tag->linkTo(["news", "Go back to overview"]) ?>
	</p>
</div>
<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
	[
		"news/create",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]
);
?>

<!--	Below-->
<!--	Must be deleted when you can log in-->

<div class="form-group">
	<label for="fieldName" class="col-sm-2 control-label">users_id</label>
	<div class="col-sm-3">
		<?php echo $this->tag->textField(["users_id", "size" => 30, "class" => "form-control", "id" => "fieldUsers_id"]) ?>
	</div>
</div>

<!--	Above must be deleted when you can log in-->

<div class="form-group">
	<label for="fieldName" class="col-sm-2 control-label">Name</label>
	<div class="col-sm-3">
		<?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldMessage" class="col-sm-2 control-label">Message</label>
	<div class="col-sm-10">
		<?php echo $this->tag->textField(["message", "size" => 30, "class" => "form-control", "id" => "fieldMessage"]) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?php echo $this->tag->endForm(); ?>
