<div class="page-header">
    <h1>
        Confirmation
    </h1>
</div>

<?php echo $this->getContent(); ?>


<?php
echo $this->tag->form(
    [
        "characters/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="row">
    <table class="confirmchar">
        <tbody>
            <td>
                <li class="confirmtag"><?php echo ucfirst($name) ?></li>
                <li>
                    <img src="/prog2-1/img/<?= $class?>_Crest.png" alt="lol" style="opacity:0.2;margin-right:5px">
                    <img src="/prog2-1/img/<?= $class?>_Crest.png" alt="lol">
                    <img src="/prog2-1/img/<?= $class?>_Crest.png" alt="lol" style="opacity:0.2">
                </li>
<!--                <img src="/prog2-1/img/druid_Crest.png" alt="lol">-->
                <li class="confirmtag"><?php echo ucfirst($class) ?>, <?php echo ucfirst($role) ?> </li>
            </td>
        </tbody>
    </table>
</div>

<div class="form-group">
    <div class="col-sm-3">
        <?php echo $this->tag->hiddenField(["name", "size" => 30, "class" => "form-control", "id" => "fieldUsers_id", "value" => "$name"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-3">
        <?php echo $this->tag->hiddenField(["class", "size" => 30, "class" => "form-control", "id" => "fieldUsers_id", "value" => "$class"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-3">
        <?php echo $this->tag->hiddenField(["role", "size" => 30, "class" => "form-control", "id" => "fieldUsers_id", "value" => "$role"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Confirm!", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
