<div class="page-header">
	<h1>
		Characters
	</h1>
	<!--	Create if statement that only shows when logged in and admin+-->
	<p>
		<i class="fa fa-plus" aria-hidden="true"></i> <?php echo $this->tag->linkTo(["characters/new", "Create new Character"]) ?>
	</p>
</div>

<?php echo $this->getContent(); ?>

<div class="btn-group" id="sort">
	<a class="btn btn-default" href="#">
		<i class="fa fa-sort-alpha-asc" title="Align Left"> Character name</i>
	</a>
	<a class="btn btn-default" href="#">
		<i class="fa fa-align-center" title="Align Center"> Class</i>
	</a>
	<a class="btn btn-default" href="#">
		<i class="fa fa-align-right" title="Align Right"> Role</i>
	</a>
</div>


<div class="row">
	<table class="characters">
		<tbody>
		<?php foreach ($characters as $character):
			$class = $character->class;
		?>
			<td>
				<li><img src="img/<?= $class?>_Crest.png" alt="lol"></li>
				<li><?php echo ucfirst($character->name) ?></li>
				<li><?php echo ucfirst($character->spec) ?></li>
			</td>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<!--<div class="row">-->
<!--	<table class="characters">-->
<!--		<tbody>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		</tbody>-->
<!--	</table>-->
<!--</div>-->