<div class="page-header">
	<h1>
		Characters
	</h1>
	<!--	Create if statement that only shows when logged in and admin+-->
	<p>
		<i class="fa fa-plus" aria-hidden="true"></i> <?php echo $this->tag->linkTo(["characters/new", "Create new Character"]) ?>
	</p>
</div>

<?php echo $this->getContent(); ?>

<!--Character main note-->
<?php $chars = count($characters); ?>
<div class="mainnote">
	<p>
		Currently you have <?php echo $chars ?> characters.
	</p>
	<?php if($chars >= 6) {
		echo "It seems like you have over 5 characters. You can now select a main ";
		echo $this->tag->linkTo(["characters/main", "here"]);
	}
	?>
</div>

<!--End of character main note-->
<div class="row">
	<table class="characters">
		<tbody>
		<?php foreach ($characters as $character):
			$class = $character->class;
		?>
			<td>
				<li><img src="img/<?= $class?>_Crest.png" alt="lol"></li>
				<li><?php echo ucfirst($character->name) ?></li>
				<li><?php echo ucfirst($character->spec) ?></li>
				<li><?php echo ucfirst($character->main) ?></li>
			</td>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>

<!--<div class="row">-->
<!--	<table class="characters">-->
<!--		<tbody>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		<td>-->
<!--			<li><img src="img/--><?//= $class?><!--_Crest.png" alt="lol"></li>-->
<!--			<li>--><?php //echo $character->name ?><!--</li>-->
<!--			<li>--><?php //echo $character->spec ?><!--</li>-->
<!--		</td>-->
<!--		</tbody>-->
<!--	</table>-->
<!--</div>-->