<div class="page-header">
    <h1>
        Create new character
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["characters", "Go back to overview"]) ?>
    </p>
</div>
<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "characters/confirm",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<!--	Below-->
<!--	Must be deleted when you can log in-->

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Character name</label>
    <div class="col-sm-3">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldUsers_id"]) ?>
    </div>
</div>

<!--	Above must be deleted when you can log in-->

<div class="form-group">
    <label for="fieldRank" class="col-sm-2 control-label">Class</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(
            [
                "class",
                [
                    "DeathKnight" => "Death Knight",
                    "DemonHunter" => "Demon Hunter",
                    "Druid" => "Druid",
                    "Hunter" => "Hunter",
                    "Mage" => "Mage",
                    "Monk" => "Monk",
                    "Paladin" => "Paladin",
                    "Priest" => "Priest",
                    "Rogue" => "Rogue",
                    "Shaman" => "Shaman",
                    "Warlock" => "Warlock",
                    "Warrior" => "Warrior",
                ]
            ]
        );
        ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRank" class="col-sm-2 control-label">Role</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(
            [
                "role",
                [
                    "Damage" => "Damage dealer",
                    "Healer" => "Healer",
                    "Tank" => "Tank",
                ]
            ]
        );
        ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
