<div class="page-header">
    <h1>
        Login
    </h1>
    <!--	Create if statement that only shows when logged in and admin+-->
    <p>
        <?php echo $this->tag->linkTo(["index", "Back to home"]) ?>
    </p>
</div>

<?php echo $this->getContent(); ?>


<?php
echo $this->tag->form(
    [
        "login/login",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-1 control-label">Username</label>
    <div class="col-sm-4">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "username"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-1 control-label">Password</label>
    <div class="col-sm-4">
        <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "password"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
        <?php echo $this->tag->submitButton(["Login", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>